global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-employees-departments'
    scrape_interval: 5s
    static_configs:
      - targets: ['app:8080']
        labels:
          service: 'api-employees-departments'
          environment: 'development'
